import type { Metadata } from "next";
import { Zalando_Sans, Geist } from "next/font/google";
import "./style/globals.css";


const zalandoSans = Zalando_Sans({
  subsets: ["latin"],
  variable:"--font-zalando",
  fallback: ["system-ui", "arial", "sans-serif"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased font-sans ${zalandoSans.variable} `}
    >
      <body className="">
        {children}
      </body>
    </html>
  );
}
