import type { Metadata } from "next";
import { Zalando_Sans, Geist } from "next/font/google";
import "./style/globals.css";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const zalandoSans = Zalando_Sans({
  variable: "--font-zalando-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${zalandoSans.variable} font-sans ${geist.variable}`}
    >
      <body className="">
        {children}
      </body>
    </html>
  );
}
